In [ ]:
# Learn array operations

In [3]:
import numpy

u = numpy.array((0,1,2,3,4,5))
print(u)
# u = numpy.array(range(6))
# print(u) lol same

for i in range(1,len(u)): # range(1,6) -> 1 to 5
    print(u[i]-u[i-1])

[0 1 2 3 4 5]
1
1
1
1
1


In [4]:
u[1:]

array([1, 2, 3, 4, 5])

In [7]:
u[0:-1]

array([0, 1, 2, 3, 4])

In [9]:
u[1:]-u[0:-1]

array([1, 1, 1, 1, 1])

In [10]:
nx = 81
ny = 81
nt = 100
c = 1
dx = 2 / (nx - 1)
dy = 2 / (ny - 1)
sigma = 0.2
dt = sigma * dx

x = numpy.linspace(0, 2, nx)
y = numpy.linspace(0, 2, ny)

u = numpy.ones((ny, nx))
print(u)
un = numpy.ones((ny, nx))

u[int(.5 / dy): int(1 / dy + 1), int(.5 / dx):int(1 / dx + 1)] = 2

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [13]:
%%timeit
u = numpy.ones((ny, nx))
u[int(.5 / dy): int(1 / dy + 1), int(.5 / dx):int(1 / dx + 1)] = 2

for n in range(nt+1):
    un = u.copy()
    row, col = u.shape # MATLAB equiv is size(u)
    for j in range(1, row):
        for i in range(1, col):
            u[j, i] = (un[j, i] - (c * dt / dx * 
                                  (un[j, i] - un[j, i - 1])) - 
                                  (c * dt / dy * 
                                   (un[j, i] - un[j - 1, i])))
            u[0, :] = 1
            u[-1, :] = 1
            u[:, 0] = 1
            u[:, -1] = 1


4.13 s ± 366 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
%%timeit
u = numpy.ones((ny, nx))
u[int(.5 / dy): int(1 / dy + 1), int(.5 / dx):int(1 / dx + 1)] = 2

for n in range(nt+1):
    un = u.copy()
    u[1:,1:] = (un[1:, 1:] - (c * dt / dx * (un[1:, 1:] - un[1:, 0:-1])) -
                              (c * dt / dy * (un[1:, 1:] - un[0:-1, 1:])))
    u[0, :] = 1
    u[-1, :] = 1
    u[:, 0] = 1
    u[:, -1] = 1

7.42 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
